// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearDiscordPresence():Promise<void>;

export function CloseWindow():Promise<void>;

export function ConnectDiscord(arg1:string):Promise<void>;

export function GetDuration():Promise<number>;

export function GetLastServerId():Promise<string>;

export function GetPosition():Promise<number>;

export function GetServers():Promise<string>;

export function IsWindowMaximized():Promise<boolean>;

export function LoadQueue():Promise<string>;

export function MaximizeWindow():Promise<void>;

export function MinimizeWindow():Promise<void>;

export function OpenExternal(arg1:string):Promise<void>;

export function Pause():Promise<void>;

export function Play(arg1:string,arg2:string):Promise<void>;

export function Resume():Promise<void>;

export function SaveQueue(arg1:string):Promise<void>;

export function SaveServers(arg1:string):Promise<void>;

export function Seek(arg1:number):Promise<void>;

export function SetLastServerId(arg1:string):Promise<void>;

export function SetMediaMetadata(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SetVolume(arg1:number):Promise<void>;

export function ShowOpenDialog(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ShowSaveDialog(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Stop():Promise<void>;

export function UpdateDiscordPresence(arg1:string):Promise<void>;
