// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearDiscordPresence() {
  return window['go']['main']['App']['ClearDiscordPresence']();
}

export function CloseWindow() {
  return window['go']['main']['App']['CloseWindow']();
}

export function ConnectDiscord(arg1) {
  return window['go']['main']['App']['ConnectDiscord'](arg1);
}

export function GetDuration() {
  return window['go']['main']['App']['GetDuration']();
}

export function GetLastServerId() {
  return window['go']['main']['App']['GetLastServerId']();
}

export function GetPosition() {
  return window['go']['main']['App']['GetPosition']();
}

export function GetServers() {
  return window['go']['main']['App']['GetServers']();
}

export function IsWindowMaximized() {
  return window['go']['main']['App']['IsWindowMaximized']();
}

export function LoadQueue() {
  return window['go']['main']['App']['LoadQueue']();
}

export function MaximizeWindow() {
  return window['go']['main']['App']['MaximizeWindow']();
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function Pause() {
  return window['go']['main']['App']['Pause']();
}

export function Play(arg1, arg2) {
  return window['go']['main']['App']['Play'](arg1, arg2);
}

export function Resume() {
  return window['go']['main']['App']['Resume']();
}

export function SaveQueue(arg1) {
  return window['go']['main']['App']['SaveQueue'](arg1);
}

export function SaveServers(arg1) {
  return window['go']['main']['App']['SaveServers'](arg1);
}

export function Seek(arg1) {
  return window['go']['main']['App']['Seek'](arg1);
}

export function SetLastServerId(arg1) {
  return window['go']['main']['App']['SetLastServerId'](arg1);
}

export function SetMediaMetadata(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetMediaMetadata'](arg1, arg2, arg3, arg4);
}

export function SetVolume(arg1) {
  return window['go']['main']['App']['SetVolume'](arg1);
}

export function ShowOpenDialog(arg1, arg2, arg3) {
  return window['go']['main']['App']['ShowOpenDialog'](arg1, arg2, arg3);
}

export function ShowSaveDialog(arg1, arg2, arg3) {
  return window['go']['main']['App']['ShowSaveDialog'](arg1, arg2, arg3);
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}

export function UpdateDiscordPresence(arg1) {
  return window['go']['main']['App']['UpdateDiscordPresence'](arg1);
}
